version: "3.9"
services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    ports:
      - "443:443"
    environment:
      - DOMAIN_NAME
      - SSL_SERVER_CERT
      - SSL_SERVER_KEY
    networks:
      - internal
    depends_on:
      - wordpress
    restart: on-failure
    init: true
  wordpress:
    build: ./requirements/wordpress
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
    image: wordpress
    hostname: wordpress
    volumes:
      - wp-volume:/var/www/html/wordpress
    networks:
      - internal
    expose:
      - 9000
    depends_on:
      - mariadb
    restart: on-failure
    init: true
  mariadb:
    build: ./requirements/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
    image: mariadb
    hostname: mariadb
    volumes:
      - db-volume:/var/lib/mysql
    expose:
      - 3306
    networks:
      - internal
    restart: on-failure
    init: true
networks:
  internal:
volumes:
  wp-volume: # github.com/moby/issues/19990
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${WP_VOLUME_DIR}"
  db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${DB_VOLUME_DIR}"

