version: "3.9"
services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    ports:
      - "443:443"
    environment:
      - DOMAIN_NAME
      - SSL_SERVER_CERT
      - SSL_SERVER_KEY
    networks:
      - internal
    depends_on:
      - wordpress
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    hostname: wordpress
    volumes:
      - "${WP_VOLUME_DIR}:/var/www/html/wordpress/wp-content"
    networks:
      - internal
    expose:
      - 9000
    depends_on:
      - mariadb
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    hostname: mariadb
    #tty: true
    #volumes:
    #  - "${DB_VOLUME_DIR}:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
    expose:
      - 3306
    networks:
      - internal
networks:
  internal:
    # driver: ''

