version: "3.9"
services:
  nginx:
    build:
      context: ./requirements/nginx
      args:
        - DOMAIN_NAME
    image: nginx
    ports:
      - "443:443"
    environment:
      - SSL_SERVER_CERT
      - SSL_SERVER_KEY
    networks:
      - internal
    depends_on:
      - wordpress
    restart: on-failure
    init: true
  wordpress:
    build:
      context: ./requirements/wordpress
      args:
        - MYSQL_USER
        - MYSQL_PASSWORD
    environment:
      - DOMAIN_NAME
      - WP_PAGE_NAME
      - WP_ADMIN_USER
      - WP_ADMIN_PASSWORD
      - WP_ADMIN_EMAIL
    image: wordpress
    hostname: wordpress
    volumes:
      - wp-volume:/var/www/html
    networks:
      - internal
    expose:
      - 9000
    depends_on:
      - mariadb
      - redis
    restart: on-failure
    init: true
  mariadb:
    build: ./requirements/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
    image: mariadb
    hostname: mariadb
    volumes:
      - db-volume:/var/lib/mysql
    expose:
      - 3306
    networks:
      - internal
    restart: on-failure
    init: true
  redis:
    build: ./requirements/bonus/redis
    image: redis
    hostname: redis
    expose:
      - 6379
    networks:
      - internal
    restart: on-failure
    init: true
  ftp-server:
    build: ./requirements/bonus/ftp-server
    image: ftp-server
    hostname: ftp-server
    ports:
      - "20:20"
      - "21:21"
    environment:
      - FTP_USER
      - FTP_PASSWORD
    volumes:
      - "wp-volume:/home/${FTP_USER}"
    networks:
      - internal
    restart: on-failure
    init: true
networks:
  internal:
volumes:
  wp-volume: # github.com/moby/issues/19990
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${WP_VOLUME_DIR}"
  db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${DB_VOLUME_DIR}"
